### ISSUE TITLE
Push 1.3.x cookbook versions to supermarket

### ISSUE THREAD

**Issue by patcon** [lusis/chef-kibana#89]
Was going to submit a PR to make the installation instructions for kibana v4 vs v3 more clear, but realized that this fails:

```rb
# Berksfile

cookbook 'kibana_lwrp', '~> 1.3.0'
```

Any reason these couldn't be pushed? I can imagine some wonkiness on supermarket that makes pushing old versions unfavoured, but if so, then I can poked around about that.

Cheers!

EDIT: I do realize it can be done via git/github keys, but then we lose version constraints, so it's more brittle :)

**Comment by spuder** [comment]
+1
Looks like 0.1.8 is the latest in the supermarket, but 2.0.6 is the latest metadata.rb

**Comment by martinb3** [comment]
Hi @patcon -- actually, because the cookbook was renamed from `kibana` to `kibana_lwrp`, we can't push the older versions to Supermarket. It would reject them since we don't have access to the 'kibana' cookbook already there. It's why it was renamed in the first place -- previously, everyone was adding Berkshelf entries for it _everywhere_.

https://github.com/lusis/chef-kibana/blob/KIBANA3/metadata.rb

Sorry to be the bearer of bad news. Cheers!
